### ISSUE TITLE
Suggestions Broken in DMS

### ISSUE THREAD

**Issue by mebrooks01** [BuildTheEarth/main-bot#288]
When attempting to make a suggestion in DMS the bot errors

seems to be attempting to get the ID of an object that does not exist
```log
ERROR: DMs (Anonymous) tried to run 'suggest' command:

    TypeError: Cannot read properties of null (reading 'id')

        at Command.run (/home/bots/main-bot/dist/commands/suggest.js:98:44)

        at processTicksAndRejections (node:internal/process/task_queues:96:5)

        at async Client.default_1 (/home/bots/main-bot/dist/events/messageCreate.js:76:13)
```

**Comment by mebrooks01** [comment]
fixed with PR #290
