### ISSUE TITLE
aoutmod except add broken

### ISSUE THREAD

**Issue by mebrooks01** [BuildTheEarth/main-bot#310]

**Comment by XboxBedrock** [comment]
Its there just uh the response says err

**Comment by Crafter-Y** [comment]
Before:


Command: /automod except list
![grafik](https://user-images.githubusercontent.com/71288761/155844473-5450d2d0-e909-4dd4-9031-6a91eb490f42.png)

Database:
![grafik](https://user-images.githubusercontent.com/71288761/155844496-449f28d2-1bf1-44ca-9f66-1c39b14ce7ac.png)
(empty)


Executing the Command:


Command: /automod except add Testing
![grafik](https://user-images.githubusercontent.com/71288761/155844557-e8ba5741-2a8d-459a-be5f-f3309698240b.png)

Database:
![grafik](https://user-images.githubusercontent.com/71288761/155844579-dbb27975-bbe7-4e98-8917-b51d57d61596.png)
(one Entry)



I think this is the expected behaviour.

**Comment by XboxBedrock** [comment]
[2022-02-26 01:57:04] ERROR: Moderator Mebrooks01#7682 tried to run 'automod' command:

    QueryFailedError: Duplicate entry 'Pippen is' for key 'PRIMARY'

        at QueryFailedError.TypeORMError [as constructor] (/etc/buildtheearth/main-bot/node_modules/typeorm/error/TypeORMError.js:9:28)

        at new QueryFailedError (/etc/buildtheearth/main-bot/node_modules/typeorm/error/QueryFailedError.js:13:28)

        at Query.onResult (/etc/buildtheearth/main-bot/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:193:57)

        at Query.execute (/etc/buildtheearth/main-bot/node_modules/mysql2/lib/commands/command.js:31:14)

        at PoolConnection.handlePacket (/etc/buildtheearth/main-bot/node_modules/mysql2/lib/connection.js:456:32)

        at PacketParser.onPacket (/etc/buildtheearth/main-bot/node_modules/mysql2/lib/connection.js:85:12)

        at PacketParser.executeStart (/etc/buildtheearth/main-bot/node_modules/mysql2/lib/packet_parser.js:75:16)

        at Socket.<anonymous> (/etc/buildtheearth/main-bot/node_modules/mysql2/lib/connection.js:92:25)

        at Socket.emit (node:events:520:28)

        at addChunk (node:internal/streams/readable:315:12)
        
Seems to be a duplicate entry issue
